package com.github.leyland.letool.data.core;

import com.github.leyland.letool.data.annotation.Column;
import com.github.leyland.letool.data.annotation.Id;
import com.github.leyland.letool.data.annotation.Table;
import com.github.leyland.letool.data.config.DataProperties;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.DriverManagerDataSource;

import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * {@link LetoolTemplate} 的 H2/JDBC 集成测试。
 *
 * <p>使用本地内存 H2 数据库验证真实 JDBC round-trip，覆盖方言检测、主键回填、
 * 注解映射、Lambda 查询和分页 SQL。</p>
 */
class DataH2IntegrationTest {

    private JdbcTemplate jdbcTemplate;
    private LetoolTemplate letoolTemplate;

    /**
     * 每个测试使用独立内存库，避免数据互相影响。
     */
    @BeforeEach
    void setUp() {
        String databaseName = "letool_data_" + System.nanoTime();
        DriverManagerDataSource dataSource = new DriverManagerDataSource();
        dataSource.setDriverClassName("org.h2.Driver");
        dataSource.setUrl("jdbc:h2:mem:" + databaseName + ";DB_CLOSE_DELAY=-1");
        dataSource.setUsername("sa");
        dataSource.setPassword("");

        jdbcTemplate = new JdbcTemplate(dataSource);
        jdbcTemplate.execute("""
                CREATE TABLE demo_user (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    user_name VARCHAR(64) NOT NULL,
                    age INT NOT NULL,
                    status VARCHAR(32) NOT NULL
                )
                """);
        letoolTemplate = new LetoolTemplate(jdbcTemplate, new DataProperties());
    }

    /**
     * H2 JDBC URL 应识别为 H2 方言，而不是静默回退到 MySQL。
     */
    @Test
    void shouldDetectH2Dialect() {
        assertThat(letoolTemplate.getDialect().getDatabaseType()).isEqualTo("H2");
        assertThat(letoolTemplate.getDialect().buildPaginationSql("SELECT * FROM demo_user", 10, 5))
                .isEqualTo("SELECT * FROM demo_user LIMIT 5 OFFSET 10");
    }

    /**
     * 验证 LetoolTemplate 能对真实 H2 数据库执行 CRUD、Lambda 条件和分页查询。
     */
    @Test
    void shouldPerformCrudLambdaQueryAndPagingAgainstH2() {
        DemoUser user = new DemoUser(null, "Alice", 28, "ACTIVE");

        int inserted = letoolTemplate.insert(user);

        assertThat(inserted).isEqualTo(1);
        assertThat(user.getId()).isNotNull();

        DemoUser selected = letoolTemplate.selectById(DemoUser.class, user.getId());
        assertThat(selected.getUserName()).isEqualTo("Alice");
        assertThat(selected.getAge()).isEqualTo(28);
        assertThat(selected.getStatus()).isEqualTo("ACTIVE");

        user.setAge(29);
        assertThat(letoolTemplate.update(user)).isEqualTo(1);

        List<DemoUser> queried = letoolTemplate.selectList(
                letoolTemplate.lambdaQuery(DemoUser.class)
                        .eq(DemoUser::getStatus, "ACTIVE")
                        .like(DemoUser::getUserName, "Ali")
                        .orderByDesc(DemoUser::getAge));
        assertThat(queried).hasSize(1);
        assertThat(queried.get(0).getAge()).isEqualTo(29);

        PaginationResult<DemoUser> page = letoolTemplate.selectPage(
                letoolTemplate.lambdaQuery(DemoUser.class)
                        .ge(DemoUser::getAge, 18)
                        .orderByAsc(DemoUser::getId),
                1,
                10);
        assertThat(page.getTotal()).isEqualTo(1);
        assertThat(page.getRecords()).extracting(DemoUser::getUserName).containsExactly("Alice");

        assertThat(letoolTemplate.deleteById(DemoUser.class, user.getId())).isEqualTo(1);
        assertThat(letoolTemplate.selectById(DemoUser.class, user.getId())).isNull();
    }

    /**
     * H2 集成测试用实体。
     */
    @Table("demo_user")
    static class DemoUser {

        @Id
        private Long id;

        @Column("user_name")
        private String userName;

        private Integer age;

        private String status;

        DemoUser() {
        }

        DemoUser(Long id, String userName, Integer age, String status) {
            this.id = id;
            this.userName = userName;
            this.age = age;
            this.status = status;
        }

        Long getId() {
            return id;
        }

        void setId(Long id) {
            this.id = id;
        }

        String getUserName() {
            return userName;
        }

        void setUserName(String userName) {
            this.userName = userName;
        }

        Integer getAge() {
            return age;
        }

        void setAge(Integer age) {
            this.age = age;
        }

        String getStatus() {
            return status;
        }

        void setStatus(String status) {
            this.status = status;
        }
    }
}
