package com.github.leyland.letool.monitor.metrics;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

@DisplayName("JvmMetricsSnapshot JVM 指标快照测试")
class JvmMetricsSnapshotTest {

    @Nested
    @DisplayName("构造方法和 getter")
    class ConstructorTests {

        @Test
        @DisplayName("完整构造函数创建快照")
        void fullConstructor() {
            JvmMetricsSnapshot snapshot = new JvmMetricsSnapshot(
                    536870912L,    // 512MB heap used
                    1073741824L,   // 1GB heap max
                    67108864L,     // 64MB non-heap
                    25,            // 25 active threads
                    5,             // 5 daemon threads
                    0.75,          // 75% CPU
                    3600000L,      // 1 hour uptime
                    100,           // 100 GCs
                    5000L          // 5s GC time
            );

            assertEquals(536870912L, snapshot.getHeapUsedBytes());
            assertEquals(1073741824L, snapshot.getHeapMaxBytes());
            assertEquals(67108864L, snapshot.getNonHeapUsedBytes());
            assertEquals(25, snapshot.getThreadCount());
            assertEquals(5, snapshot.getDaemonThreadCount());
            assertEquals(0.75, snapshot.getCpuLoad(), 0.001);
            assertEquals(3600000L, snapshot.getUptimeMs());
            assertEquals(100, snapshot.getGcCount());
            assertEquals(5000L, snapshot.getGcTimeMs());
            assertNotNull(snapshot.getTimestamp());
        }

        @Test
        @DisplayName("timestamp 自动生成为当前时间")
        void timestampAutoGenerated() {
            JvmMetricsSnapshot snapshot = new JvmMetricsSnapshot(
                    0, 0, 0, 0, 0, 0, 0, 0, 0);
            assertNotNull(snapshot.getTimestamp());
            // Should be within last second
            assertTrue(java.time.Duration.between(snapshot.getTimestamp(), java.time.LocalDateTime.now()).getSeconds() < 5);
        }
    }

    @Nested
    @DisplayName("便捷计算方法")
    class ConvenienceMethodTests {

        @Test
        @DisplayName("getHeapUsagePercent 计算堆内存使用率")
        void heapUsagePercent() {
            JvmMetricsSnapshot snapshot = new JvmMetricsSnapshot(
                    536870912L, 1073741824L, 0, 0, 0, 0, 0, 0, 0);
            assertEquals(0.5, snapshot.getHeapUsagePercent(), 0.001);
        }

        @Test
        @DisplayName("heapMaxBytes 为 0 时返回 0")
        void heapUsagePercentZeroMax() {
            JvmMetricsSnapshot snapshot = new JvmMetricsSnapshot(
                    100, 0, 0, 0, 0, 0, 0, 0, 0);
            assertEquals(0.0, snapshot.getHeapUsagePercent(), 0.001);
        }

        @Test
        @DisplayName("heapMaxBytes 为负数时返回 0")
        void heapUsagePercentNegativeMax() {
            JvmMetricsSnapshot snapshot = new JvmMetricsSnapshot(
                    100, -1, 0, 0, 0, 0, 0, 0, 0);
            assertEquals(0.0, snapshot.getHeapUsagePercent(), 0.001);
        }

        @Test
        @DisplayName("getTotalThreadCount 活跃 + 守护")
        void totalThreadCount() {
            JvmMetricsSnapshot snapshot = new JvmMetricsSnapshot(
                    0, 0, 0, 30, 10, 0, 0, 0, 0);
            assertEquals(40, snapshot.getTotalThreadCount());
        }

        @Test
        @DisplayName("toString 包含关键指标")
        void toStringContainsMetrics() {
            JvmMetricsSnapshot snapshot = new JvmMetricsSnapshot(
                    1073741824L, 2147483648L, 134217728L, 25, 5, 0.50, 60000L, 50, 2000L);
            String str = snapshot.toString();
            assertTrue(str.contains("1024"));     // heap used in MB
            assertTrue(str.contains("2048"));     // heap max in MB
            assertTrue(str.contains("25"));       // thread count
            assertTrue(str.contains("5"));        // daemon count
            assertTrue(str.contains("50.00"));    // CPU percentage
            assertTrue(str.contains("60"));       // uptime seconds
            assertTrue(str.contains("50"));       // GC count
            assertTrue(str.contains("2000"));     // GC time
        }
    }
}
